from datetime import timedelta
from typing import Protocol, runtime_checkable

from src.domain import Correction, DecisionRecord, EmailMessage, TriageResult


@runtime_checkable
class DecisionStore(Protocol):
    def record_decision(self, email: EmailMessage, triage: TriageResult, route: str) -> None: ...

    def get(self, message_id: str) -> DecisionRecord | None: ...

    def attach_chat_message(self, message_id: str, chat_message_id: int) -> None: ...

    def find_by_chat_message(self, chat_message_id: int) -> DecisionRecord | None: ...

    def record_feedback(self, message_id: str, verdict: str) -> bool: ...

    def recent_corrections(self, limit: int) -> list[Correction]: ...

    def feedback_counts(self) -> dict[str, int]: ...

    def mark_alerted(self, message_id: str) -> None: ...

    def was_alerted(self, message_id: str, within_seconds: float | None = None) -> bool: ...

    def get_state(self, key: str) -> str | None: ...

    def set_state(self, key: str, value: str) -> None: ...

    def prune(self, older_than: timedelta) -> int: ...

    def backup(self, destination: str) -> None:
        """Writes a consistent, verified copy to `destination`; raises when it cannot."""
        ...

    def close(self) -> None: ...
